dist: trusty
language: ruby
rvm:
  - 2.3
  - 2.4

gemfile:
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_5_1.gemfile

services:
  - postgresql

before_script:
  - psql -c 'CREATE DATABASE iknow_view_models;' -U postgres

addons:
  postgresql: "9.6"

notifications:
  email: false
