dist: trusty
sudo: false
language: ruby
cache: bundler

rvm:
  - 2.5
  - 2.6

gemfile:
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_5_2.gemfile

addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
      - postgresql-server-dev-10
env:
  global:
    - PGPORT=5433

before_install:
  - gem update --system
  - gem install bundler

before_script:
  - psql -c 'CREATE DATABASE iknow_view_models;'

notifications:
  email: false
