dist: trusty
language: ruby
rvm:
  - 2.5
  - 2.6

gemfile:
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_5_2.gemfile

services:
  - postgresql

before_install:
  - gem update --system

before_script:
  - psql -c 'CREATE DATABASE iknow_view_models;' -U postgres

addons:
  postgresql: "9.6"

notifications:
  email: false
